Actions file updated

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,8 +48,8 @@ jobs:
       # Add Server to Known Hosts
       - name: Add Server to Known Hosts
         run: |
-          if ! ssh-keygen -F ${{ vars.SERVER_IP }} > /dev/null; then
-            ssh-keyscan -H ${{ vars.SERVER_IP }} >> ~/.ssh/known_hosts
+          if ! ssh-keyscan -H ${vars.SERVER_IP} >> ~/.ssh/known_hosts; then
+            echo "Failed to add server to known hosts"
           fi
           chmod 600 ~/.ssh/known_hosts
 
