Actions file updated

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,23 +40,17 @@ jobs:
         run: |
           ls -R src/modern/.vitepress/dist || echo "Modern build output directory not found"
           ls -R src/classic/.vitepress/dist || echo "Classic build output directory not found"
-      - name: Upload Modern Build Artifact
-        uses: actions/upload-artifact@v3
+      - name: Upload Modern Artifact
+        uses: actions/upload-pages-artifact@v3
         with:
-          name: modern-build
           path: src/modern/.vitepress/dist
-      - name: Upload Classic Build Artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: classic-build
-          path: src/classic/.vitepress/dist
 
   # Deploy modern version to GitHub Pages
   deploy-modern:
     environment:
       name: github-pages
       url: https://support.mantishub.com
-    needs: build
+    needs: build-modern
     runs-on: ubuntu-latest
     steps:
       - name: Deploy Modern to GitHub Pages
@@ -64,29 +58,35 @@ jobs:
         uses: actions/deploy-pages@v4
 
   deploy-to-server:
-    needs: build
+    needs: build-modern
     runs-on: ubuntu-latest
     environment: production
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Download Modern Build Artifact
-        uses: actions/download-artifact@v3
+      - name: Setup Node
+        uses: actions/setup-node@v4
         with:
-          name: modern-build
-          path: src/modern/.vitepress/dist
+          node-version: 20
 
-      - name: Download Classic Build Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: classic-build
-          path: src/classic/.vitepress/dist
+      - name: Install Dependencies
+        run: npm ci
 
       - name: Debug Directories
         run: |
           ls -R src/modern || echo "src/modern directory not found"
           ls -R src/classic || echo "src/classic directory not found"
+
+      - name: Build Modern and Classic Versions
+        run: |
+          npm run build:modern
+          npm run build:classic
+
+      - name: Debug Build Outputs
+        run: |
+          ls -R src/modern/.vitepress/dist || echo "Modern build output directory not found"
+          ls -R src/classic/.vitepress/dist || echo "Classic build output directory not found"
 
       - name: Set up SSH Key and Agent
         env:
@@ -119,7 +119,7 @@ jobs:
             rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete src/modern/.vitepress/dist/ forge@${{ vars.SERVER_IP }}:/var/www/modern/
           else
             echo "Modern build output directory missing. Skipping deployment."
-            exit 1
+            exit 1                                         
           fi
 
       - name: Deploy Classic Files
